title: Stuart Jennings # your name (or website title) here
logo: "/images/stu-circle.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist 
  <br><br>
  Building my portfolio... Stay tuned! 
  <br><br>
  <a href="https://www.linkedin.com/in/stuart-jennings-92bb37192/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
