title: Stuart Jennings # your name (or website title) here
logo: "/images/stu-circle.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Current BYU student and Forecasting Specialist for doTERRA. Pursuing Data Science career.
  <br><br>
  I love data! I've always been an extremely analytical person, so it was only natural for me to pursue a future in data analytics and data science at BYU. I love being able to take messy data, transform it, and use it to tell a story and provide insights. I'm excited to enter the professional world of data science and continue learning about data each day! 
  <br><br>
  <a href="https://www.linkedin.com/in/stuart-jennings-92bb37192/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
